{"name": "test_login_courier_negative[\\u043e\\u0442\\u0441\\u0443\\u0442\\u0441\\u0442\\u0432\\u0443\\u0435\\u0442 \\u043f\\u0430\\u0440\\u043e\\u043b\\u044c]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 504 == 400\n +  where 504 = <Response [504]>.status_code", "trace": "self = <tests.test_login_courier.TestLoginCourier object at 0x0000019D8626B460>, login_data = {'login': 'test_user'}, expected_status_code = 400, expected_message = 'Недостаточно данных для входа'\n\n    @pytest.mark.parametrize(\"login_data, expected_status_code, expected_message\", [\n        ({\"login\": \"nonexistent\", \"password\": \"wrongpassword\"}, 404, \"Учетная запись не найдена\"),\n        ({\"login\": \"\", \"password\": \"65498\"}, 400, \"Недостаточно данных для входа\"),\n        ({\"login\": \"test_user\", \"password\": \"\"}, 400, \"Недостаточно данных для входа\"),\n        ({\"password\": \"65498\"}, 400, \"Недостаточно данных для входа\"),\n        ({\"login\": \"test_user\"}, 400, \"Недостаточно данных для входа\")\n    ], ids=[\n        \"недействительные логин и пароль\",\n        \"пустой логин\",\n        \"пустой пароль\",\n        \"отсутствует логин\",\n        \"отсутствует пароль\"\n    ])\n    def test_login_courier_negative(self, login_data, expected_status_code, expected_message):\n        with allure.step('Проверка негативных сценариев авторизации курьера'):\n            # Авторизация курьера\n            response = requests.post(Url.BASE_URL + Url.COURIER_LOGIN_URL, json=login_data)\n    \n>           assert response.status_code == expected_status_code\nE           assert 504 == 400\nE            +  where 504 = <Response [504]>.status_code\n\ntests\\test_login_courier.py:40: AssertionError"}, "steps": [{"name": "Проверка негативных сценариев авторизации курьера", "status": "failed", "statusDetails": {"message": "AssertionError: assert 504 == 400\n +  where 504 = <Response [504]>.status_code\n", "trace": "  File \"C:\\Users\\Татьяна\\PycharmProjects\\Sprint_7\\tests\\test_login_courier.py\", line 40, in test_login_courier_negative\n    assert response.status_code == expected_status_code\n"}, "start": 1747931949971, "stop": 1747932010118}], "parameters": [{"name": "login_data", "value": "{'login': 'test_user'}"}, {"name": "expected_status_code", "value": "400"}, {"name": "expected_message", "value": "'Недостаточно данных для входа'"}], "start": 1747931949970, "stop": 1747932010121, "uuid": "c23e4cd0-32ad-481c-b5a6-e7c3975dee93", "historyId": "7501026c906d9a016cf473a284b998f3", "testCaseId": "bddfd01ce1b818c3cd9bbefc194e4964", "fullName": "tests.test_login_courier.TestLoginCourier#test_login_courier_negative", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "DESKTOP-UJULI2B"}, {"name": "thread", "value": "10680-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}